services:
  okonbini-djnago:
    container_name: okonbini-djnago
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      - "8000:8000"
    networks:
      - app_net
    volumes:
      - .:/app
      - ./logs:/app/logs

networks:
  app_net:
    external: true
