# Generated by Django 4.2.5 on 2024-12-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okonbini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='okonbini.itemcategory'),
        ),
    ]
