# Generated by Django 4.2.5 on 2024-12-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okonbini', '0002_alter_item_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
